### ISSUE TITLE
output path

### ISSUE THREAD

**Issue by Ollipolli1909** [Genometric/MSPC#161]
Hi,
very much like MSPC. I am using it in R, and one thing I can't get to work is the outputpath. No matter what I add here, MSPC defaults to save the output into this folder:
C:\Users\username\AppData\Local\Temp

Do you know what causes this, and how to make MSPC accept my outputpath ?
Thanks,
Oliver

**Comment by MeriemBahda** [comment]
Hi @Ollipolli1909, 
I'm happy to hear that you enjoy using the rmspc package. 
I believe you might need to set the argument `keep = TRUE` when you run the mspc function in order to have files saved in the folder specified by the argument `outputPath`.

Basically, the `keep` argument determines whether the mspc function should keep or delete (i.e., put in a temporary folder )  all the files generated while running the MSPC program. When the argument `keep` is set to FALSE, all the files are created in a temporary folder, which is deleted after the R session is closed. When the argument `keep` is set to TRUE, the files are created in the folder specified by the argument `outputPath`. 
If you don't specify the value of the `keep` argument, its default value is used. The default value of the argument `keep` is defined as follows :
1.  if the input argument is a GRanges object, the default value of the `keep` argument is FALSE. 
2.  if the input argument is a character vector of the file path of input BED files, the default value of the `keep` argument is TRUE.

I hope this will answer your question. 
Meriem

**Comment by Ollipolli1909** [comment]
Sorry, completely missed that. Works now.

Cheers,
Oliver

**Comment by VJalili** [comment]
Thanks, @MeriemBahda and @Ollipolli1909, I'm closing this issue, but please feel free to reopen or create a new issue if you have a similar question.
