### ISSUE TITLE
Obtaining the actual values of 'inf's

### ISSUE THREAD

**Issue by juylmin** [Genometric/MSPC#163]
Hello, 

I just wonder if there is a way to obtain the actual values of the peaks that have p-values as infs in the resultant Consensus files. 

Thank you.

**Comment by VJalili** [comment]
MSPC reports the value (e.g., p-value or RTP) of regions/peaks in its output in _Phred_ scale, i.e., `-Log_10 (p-value)`. If the value is computed `0`, MSPC reports it `inf` in the _Phred_ scale. Please refer to https://github.com/Genometric/MSPC/issues/131 for detailed discussion around the design decision. 

Concerning p-values, the value is rounded to `0` when it is very small (significant); in C#, and accordingly in MSPC, it will be rounded to `0` if smaller than `5.0e−324` [[ref]](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types).

MSPC expects the p-values in input files to be in the Phred scale (see [this docs page for more details]( https://genometric.github.io/MSPC/docs/cli/parser/#p-value-format) for more details); hence, if you have a peak with a value such as `1000` in an input BED file in Phred scale, it will be converted to `0`.

Hence, when you get `inf`, it means the value is smaller than that can be represented on the system. 

However, if you think your values are not that small, then there is a chance that your values are in a different Phred scale than the expected default (e.g., in `-100 Log10` instead of `-1 Log 10`). Please check that, and if that is the case, you can set MSPC to read the p-values correctly by [providing](https://genometric.github.io/MSPC/docs/cli/args#input-parser-configuration) a [parser config file.](https://genometric.github.io/MSPC/docs/cli/parser/).

**Comment by juylmin** [comment]
I understand clearly. Thank you.

**Comment by VJalili** [comment]
Glad that helps. Hence I am closing this issue, but please feel free to reopen if you had a related question.
