### ISSUE TITLE
Identical consensus peaks with different thresholds

### ISSUE THREAD

**Issue by fernandoPalluzzi** [Genometric/MSPC#82]
It seems that peaks for the same transcription factor, called with different threshold values, return same consensus peak set.

**Comment by VJalili** [comment]
@fernandoPalluzzi Thank you for reporting this. 

This issue can be caused by the format of the p-values of input peaks: the default expected p-value format is `-Log10(p-value)`. Hence your peaks are in different format (e.g., `-100*Log10(p-value)`) then the thresholds may not apply correctly. 

In this case you should specify p-values format using a parser configuration file. See:
- [how to specify a configuration file path](https://genometric.github.io/MSPC/docs/cli/args#input-parser-configuration);
- [how to define a input parser configuration](https://genometric.github.io/MSPC/docs/cli/parser).
